### ISSUE TITLE
on_orion_xs_message automation trigger in config causes compilation error

### ISSUE THREAD

**Issue by allthepies** [Fabian-Schmidt/esphome-victron_ble#101]
If I include the on_orion_xs_message automation trigger in the config then I get a compilation error:

```
    # Advanced users can use `on_*_message` action. The data is in the `message` variable.
    on_battery_monitor_message:
      - logger.log: "Message from Battery Monitor."
    on_solar_charger_message:
      - logger.log: "Message from Solar Charger."
    on_orion_xs_message:
      - logger.log: "Message from OrionXS Charger."
```

```
Compiling .pioenvs/victron-ble/src/main.cpp.o
src/main.cpp:31:14: error: 'OrionXsMessageTrigger' in namespace 'esphome::victron_ble' does not name a type; did you mean 'VeBusMessageTrigger'?
   31 | victron_ble::OrionXsMessageTrigger *victron_ble_orionxsmessagetrigger_id;
      |              ^~~~~~~~~~~~~~~~~~~~~
      |              VeBusMessageTrigger
src/main.cpp: In function 'void setup()':
src/main.cpp:308:3: error: 'victron_ble_orionxsmessagetrigger_id' was not declared in this scope; did you mean 'victron_ble_solarchargermessagetrigger_id'?
  308 |   victron_ble_orionxsmessagetrigger_id = new victron_ble::OrionXsMessageTrigger(MyOrionXS);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   victron_ble_solarchargermessagetrigger_id
src/main.cpp:308:46: error: expected type-specifier
  308 |   victron_ble_orionxsmessagetrigger_id = new victron_ble::OrionXsMessageTrigger(MyOrionXS);
      |                                              ^~~~~~~~~~~
*** [.pioenvs/victron-ble/src/main.cpp.o] Error 1
========================= [FAILED] Took 25.02 seconds =========================
```
