### ISSUE TITLE
Limit Message to Home Assistant

### ISSUE THREAD

**Issue by marktroll** [Fabian-Schmidt/esphome-victron_ble#109]
Is there a possibility to reduce the amount of chatty messages??
My Victron is in a garage over a VPN and a LTE router. It sends over 500mb/week with 2 chargers connected. 
That'll run over my free traffic...

Regards,
 Markus

**Comment by sooty66** [comment]
You can add filters to chatty sensors to reduce the number of records in Home Assistant.
The current reading on my camper van smart shunt is particularly chatty so the filter below sends an average reading every 1 minute and will send a NAN if nothing is received within 2 minutes.

```
- platform: victron_ble
    victron_ble_id: MySmartShunt
    name: "SmartShunt Current"
    type: BATTERY_CURRENT
    filters:
      - throttle_average: 60s
      - timeout: 120s
```
