### ISSUE TITLE
Feedback for Phoenix inverter with dongle & MPPT

### ISSUE THREAD

**Issue by cainslie** [Fabian-Schmidt/esphome-victron_ble#17]
Just to let you know, the following code works partially with a 12/500 Phoenix inverter with dongle as well as with a 75/10 MPPT

AC Current - not sure if that's correct. It's showing 0.2A when inverter is running at about 20% load
AC Power is showing -1VA
AC Voltage is showing -97.8V (I am in a 220V country)
Battery Current is showing "Unknown"
Battery Voltage is correct.

```
esphome:
  name: victron-ble
  friendly_name: victron-ble

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Victron-Ble Fallback Hotspot"
    password: ""

esp32_ble_tracker:

victron_ble:
  - id: MyInverter
    mac_address: "-"    
    bindkey: "-"
  - id: MyMPPT
    mac_address: "-"
    bindkey: "-"

sensor:
  # MySmartShunt
  - platform: victron_ble
    victron_ble_id: MyInverter
    name: "Battery voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MyInverter
    name: "AC Power"
    type: AC_APPARENT_POWER
  - platform: victron_ble
    victron_ble_id: MyInverter
    name: "AC Current"
    type: AC_CURRENT
  - platform: victron_ble
    victron_ble_id: MyInverter
    name: "AC Voltage"
    type: AC_VOLTAGE

  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "MPPT"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "Yield Today"
    type: YIELD_TODAY
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "PV Power"
    type: PV_POWER
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "Load Current"
    type: LOAD_CURRENT

binary_sensor:
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "MPPT is in Fault state"
    type: DEVICE_STATE_FAULT
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "MPPT has Error"
    type: CHARGER_ERROR

text_sensor:
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "MPPT state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: MyMPPT
    name: "MPPT Error reason"
    type: CHARGER_ERROR
```
