### ISSUE TITLE
Additional sensors? Switches possible?

### ISSUE THREAD

**Issue by snipah** [Fabian-Schmidt/esphome-victron_ble#2]
Hi Fabian! 

As everything is working great, I'd like to ask some questions:
1. Is it possible to implement additional sensors or is everything, that is being advertised via Victron BLE already implemented? I'm wondering, because e. g. the momentary consumption in Watts is not included. I have it implemented in Home Assistant by multiplying the current * 12V, but I assume Victron publishes this info via BLE.
2. Is you are using an advertising BLE-implementation I assume Switches are not possible, e. g. for the  load-output :)

Thanks a lot for your time and patience!

**Comment by Fabian-Schmidt** [comment]
Hi, I have implemented all possible data available in the data (and documented by Victron).
Watts current consumption you setup on the device as voltage * amps. I will provide you an example when I am on my computer later today. As for consumed Wh is complex and cannot be done accurately.


The data is only broadcasted and no changes to device settings (eg load ouput) is possible. But you could setup your MPPT rx port as load output enabled and provide the signal from your ESP (binary output) via a cable.

**Comment by Fabian-Schmidt** [comment]
Example calculation of current Watts of shunt:
```yaml
  - platform: victron_ble
    victron_ble_id: MySmartShunt
    name: "Battery voltage"
    type: BATTERY_VOLTAGE
    id: shunt_BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartShunt
    name: "Current"
    type: BATTERY_CURRENT
    id: shunt_BATTERY_CURRENT
  - platform: template
    id: shunt_WATT
    lambda: |-
      const auto voltage = id(shunt_BATTERY_VOLTAGE).state;
      const auto current = id(shunt_BATTERY_CURRENT).state;
      if(std::isnan(voltage) || std::isnan(current)) {
        return NAN;
      } else {
        return voltage * current;
      }
```
