### ISSUE TITLE
Feedback: Battery Sense and Orion Smart DCDC is working

### ISSUE THREAD

**Issue by HBK1** [Fabian-Schmidt/esphome-victron_ble#20]
Victron Battery Sense reports as Battery Monitor and presents BATTERY_VOLTAGE and TEMPERATURE.
Orion Smart DCDC needs a filter on OUTPUT_VOLTAGE since it reports 0x7FFF=32767 when engine is off=Unavalible.
Both are working ok together with a Smartshunt and MPPT on the same ESP32.

See below config for DCDC and Battery Sense:
```
victron_ble:
  - id: MySmartDcdc
    mac_address: ${smart_dcdc_mac_address}
    bindkey: ${smart_dcdc_encryption_key}
  - id: MySmartBS
    mac_address: ${smart_bs_mac_address}
    bindkey: ${smart_bs_encryption_key}

sensor:
  # MySmartDcdc
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC Input Voltage"
    type: INPUT_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC Output Voltage"
    type: OUTPUT_VOLTAGE
   # DCDC reports 0x7FFF=32767 when off=Unavalible 
    filters:
      - filter_out: 327.67

  # MySmartBS
  - platform: victron_ble
    victron_ble_id: MySmartBS
    name: "BS voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartBS
    name: "BS temperature"
    type: TEMPERATURE

binary_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC is in Fault state"
    type: DEVICE_STATE_FAULT
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC has Error"
    type: CHARGER_ERROR

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC Error reason"
    type: CHARGER_ERROR
  - platform: victron_ble
    victron_ble_id: MySmartDcdc
    name: "DCDC Off reason"
    type: OFF_REASON

```
