### ISSUE TITLE
AC Charger blue smart ip 22

### ISSUE THREAD

**Issue by wasn-eu** [Fabian-Schmidt/esphome-victron_ble#21]
Hi

any timeline when the blue smart charger ip22 will be supported?
i have a blue smart 24/12 (1) here and need to integrate it

**Comment by Fabian-Schmidt** [comment]
Does the AC Charger blue smart ip22 support the announcement protocol?

You can check by opening the Vic tron Connect App and if on the device overview page you can see status information from the device then it does support it.

Can you post a screenshot of the device overview page to help identify which fields are expected to be transmitted by the device in the announcement protocol? 

Thanks

**Comment by HBK1** [comment]
I have the Blue Smart IP22 charger and it does not support the announcement protocol.
Also running latest beta v5.92beta2.

**Comment by Fabian-Schmidt** [comment]
Can you maybe activate it on the `Product info` page? It is called `Instant readout via Bluetooth`.

If the product does not support the Bluetooth announcement (Instant readout) then there is unfortunatly nothing I can do here.

**Comment by wasn-eu** [comment]
Instant readout is not possible.
i opened my charger and found a 6pin header.

you can find the documentation here:
https://github.com/wasn-eu/Victron_BlueSmart_IP22

**Comment by Fabian-Schmidt** [comment]
Looks like the normal and very well documented victron ve direct protocol.

**Comment by wasn-eu** [comment]
Found that out too.
Now i have to find the the rx pin on the charger side. Will get my Oszilloskop out

**Comment by Fabian-Schmidt** [comment]
FYI Looks like the latest firmware version does support Instant Readout. See <https://www.victronenergy.com/live/victronconnect:beta> & <https://github.com/Fabian-Schmidt/esphome-victron_ble/issues/62>

**Comment by aavdberg** [comment]
Yes I have this charger also now and does support it with official firmware. @Fabian-Schmidt can I help you with this?

**Comment by Fabian-Schmidt** [comment]
@aavdberg Have your tried the config shared in the #62 ?

```yaml
sensor:
  # MySmart230
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Power"
    type: BATTERY_POWER
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Temp"
    type: TEMPERATURE

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 has Error"
    type: CHARGER_ERROR
```
