### ISSUE TITLE
New sensor state class: total_increasing for compatibility with Home Assistant energy dashboard

### ISSUE THREAD

**Issue by snipah** [Fabian-Schmidt/esphome-victron_ble#3]
I think it would be a great idea to add an additional state for some sensors to add compatibility for the Home Assisstant energy dashboard: [New sensor state class: total_increasing](https://developers.home-assistant.io/blog/2021/08/16/state_class_total/)

Suitable sensors would be yield_today and battery_power if I'm not mistaken.

**Comment by Fabian-Schmidt** [comment]
I have updated the default value for `yield_today` to be total_increasing.
The only other field which I consider is `consumed_ah`.
Based on my understanding of the docs (links below) is the current measurement value more important than the total value.
 - https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes
 - https://developers.home-assistant.io/docs/core/entity/sensor/#how-to-choose-state_class-and-last_reset 

If you disagree you can always overwrite the state_class for each sensor in the yaml for any sensor.

**Comment by snipah** [comment]
Thanks! I think you are right: consumed_ah and yield_today are the most suitable fields.

**Comment by Fabian-Schmidt** [comment]
The *Smart*Shunt is already perfoming the integration.
If `BATTERY_CURRENT` is positiv it is charging and when negativ it is discharging.
And the `CONSUMED_AH` and `STATE_OF_CHARGE` is the result of the integration. It is the state of the battery.
Plus the field `TIME_TO_GO` contains the expected battery runtime based on current consumption (within the settings of the smart shunt you can configure the time between 1-12 minutes to average).
So there is no need that HA is doing any integration as the *Smart*Shunt is already doing it with higher precision.

**Comment by snipah** [comment]
This sounds great, but does not help to fill the fields "Energy going into the battery" and "Energy going out of the battery", as we need kWh. This would be `CONSUMED_AH` * `STATE_OF_CHARGE`, correct?

**Comment by Fabian-Schmidt** [comment]
The example takes `CONSUMED_AH * BATTERY_VOLTAGE = Wh`. That is incorrect for batteries as the voltage fluctuates based on the current load and state of charge.
Batteries are always measured in Ah and not Wh. I don't know what HA is expecting here.

**Comment by Fabian-Schmidt** [comment]
I don't have a HA running. Based on the example it could be like this:

```yaml
  - platform: victron_ble
    victron_ble_id: MySmartShunt
    name: "Battery voltage"
    type: BATTERY_VOLTAGE
    id: shunt_BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartShunt
    name: "Consumed Ah"
    type: CONSUMED_AH
    id: shunt_CONSUMED_AH

  - platform: template
    name: "charge"
    lambda: |-
      const auto my_battery_ah = 95.0f;
      const auto ah = id(shunt_CONSUMED_AH).state;
      const auto voltage = id(shunt_BATTERY_VOLTAGE).state;
      if(std::isnan(ah) || std::isnan(voltage)) {
        return NAN;
      }
      const auto remaining_ah = my_battery_ah + ah;
      return remaining_ah * voltage;
  - platform: template
    name: "discharge"
    lambda: |-
      const auto ah = id(shunt_CONSUMED_AH).state;
      const auto voltage = id(shunt_BATTERY_VOLTAGE).state;
      if(std::isnan(ah) || std::isnan(voltage)) {
        return NAN;
      }
      return ah * voltage;
```

I consider this wrong but if HA wants it.
