### ISSUE TITLE
action ON    for shunt? same as battery_monitor?

### ISSUE THREAD

**Issue by riker65** [Fabian-Schmidt/esphome-victron_ble#31]
Hi

which of the actions are refereing to the shunt?
I expected battery Monitor, but do not see a message

```
    on_battery_monitor_message:
      - logger.log: "Message from Battery Monitor."

    on_inverter_message:
      - logger.log: "Message from Inverter."
    on_dcdc_converter_message:
      - logger.log: "Message from DC/DC Converter."
    on_smart_lithium_message:
      - logger.log: "Message from Smart Lithium."
    on_inverter_rs_message:
      - logger.log: "Message from Inverter RS."
    on_smart_battery_protect_message:
      - logger.log: "Message from Smart Battery Protect."
    on_lynx_smart_bms_message:
      - logger.log: "Message from Lynx Smart BMS."
    on_multi_rs_message:
      - logger.log: "Message from Multi RS."
    on_ve_bus_message:
      - logger.log: "Message from VE.Bus."
    on_dc_energy_meter_message:
      - logger.log: "Message from DC Energy Meter."
```
