### ISSUE TITLE
BLE and WiFi together

### ISSUE THREAD

**Issue by captain324** [Fabian-Schmidt/esphome-victron_ble#61]
Using the victron-ble.yaml code as a start, I have been able to connect to a Victron Orion Tr DC-DC Charger. With BLE and WiFi both enabled the ESP32 dev board is unstable, rebooting over and over with errors that BLE is unable to start and that it can not find the WiFi AP. I'm using an Ideaspark (Amazon) ESP32 dev board with an integrated LCD screen. With the WiFi code disabled, it works.

I read there is a coexistence module in the ESP32 code, but it is not working for me. Any suggestions?

Here is my code, still a bit rough but working ...

```
# WIP adding display stuff
# ili9xxx vs ST7789V - which driver is bettter?
# no binary sensors found
# stable? not stable with both ble and wifi

esphome:
  name: victron-ble-r2
  friendly_name: victron-ble-r2

esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
#api:
#  encryption:
#    key: "JqNKvthRY/fmdq92ESQIys/buKruo1oqUQQOr+aXcCA="

#ota:
#  - platform: esphome
#    password: "7bd2ddffda653538a1a1147ef1ca521e"

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  manual_ip: 
#    static_ip: 192.168.8.100
#    gateway: 192.168.8.1
#    subnet: 255.255.255.0
#    dns1: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Victron-Ble Fallback Hotspot"
#    password: "ptpdJHm2APPK"

esp32_ble_tracker:

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

victron_ble:
  - id: AuxBatteryCharger
    mac_address: "D9:1A:2E:DC:B1:40"    
    bindkey: "55bf7a059d157eeb4679ba9c1db31c4a"
    on_dcdc_converter_message:
      - logger.log: "Message from DC/DC Converter."

sensor:
  # DC-DC Charger
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Error Report"
    type: CHARGER_ERROR
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Device State"
    type: DEVICE_STATE
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "House Battery"
    type: INPUT_VOLTAGE
    id: input_voltage
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Off Reason"
    type: OFF_REASON
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Aux Battery"
    type: OUTPUT_VOLTAGE
    id: output_voltage

binary_sensor:
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Charger Error"
    type: CHARGER_ERROR

  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "DEVICE_STATE_OFF"
    type: DEVICE_STATE_OFF

  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "DEVICE_STATE_FAULT"   
    type: DEVICE_STATE_FAULT
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "DEVICE_STATE_BULK"
    type: DEVICE_STATE_BULK
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "DEVICE_STATE_ABSORPTION"
    type: DEVICE_STATE_ABSORPTION
    
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "DEVICE_STATE_FLOAT"
    type: DEVICE_STATE_FLOAT
    
text_sensor:
  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Charger Error"
    type: CHARGER_ERROR
    id: charger_error

  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Charger state"
    type: DEVICE_STATE
    id: charger_state

  - platform: victron_ble
    victron_ble_id: AuxBatteryCharger
    name: "Off Reason"
    type: OFF_REASON
    id: off_reason

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: ili9xxx
    model: ST7789V
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true
    dimensions:
      height: 170
      width: 320
      offset_height: 35
      offset_width: 0
    cs_pin: GPIO15
    dc_pin: GPIO02
    reset_pin: GPIO04
    invert_colors: true

    lambda: |-
      auto black = Color(0, 0, 0);
      auto red = Color(255, 0, 0);
      auto green = Color(0, 255, 0);
      auto blue = Color(0, 0, 255);
      auto white = Color(255, 255, 255);
      it.print(0, 0, id(font20), "Valiant DC-DC Charger");
      it.line(0, 20, 320, 20);
      it.printf(0, 40, id(font15), "Charger Error:   %s", id(charger_error).state.c_str());
      it.printf(0, 60, id(font15), "Charger State:   %s", id(charger_state).state.c_str());
      it.printf(0, 80, id(font15), "Off Reason: %s", id(off_reason).state.c_str());
      it.printf(0, 100, id(font15), "House Battery Voltage: %5.2f", id(input_voltage).state);
      it.printf(0, 120, id(font15), "Aux Battery Voltage: %5.2f", id(output_voltage).state);

font:
  - file: "gfonts://Roboto"
    id: font20
    size: 20
  - file: "gfonts://Roboto"
    id: font15
    size: 15
  - file: "gfonts://Roboto"
    id: font10
    size: 10
    
#captive_portal:
```
