### ISSUE TITLE
Add support for Pheonix Smart Charger

### ISSUE THREAD

**Issue by chmadkk** [Fabian-Schmidt/esphome-victron_ble#62]
Hi. 

Can i on any means be supportive with any documentation or testing regarding the Phoenix Smart Charger ? 
I have one of those in my Camper. 
And i would love to help.

**Comment by HBK1** [comment]
It is Victron that do not publish the values so you have to suggest it to Victron.
https://community.victronenergy.com/questions/187303/victron-bluetooth-advertising-protocol.html

**Comment by Fabian-Schmidt** [comment]
Does the Phoenix Smart Charger support Bluetooth and also supports Instant readout via the Victron app? So you see values for the device in the overview page before you connect to the device?

If it does then we can try to add support.

I would need VERBOSE logging with a few example values from the log. There should be a message `Encrypted message: ` in the log. And the corresponding value displayed in the Victron App for the log messages. To identify the various states.

**Comment by HBK1** [comment]
In VictronConnect v6.10beta14 the Blue Smart Charger supports Instant Readout and I saw it display Output Voltage and Output Current and Battery Voltage and Temperature.

**Comment by HBK1** [comment]
Here is screenshot of VictronConnect and Verbose log.
![230BluSmart](https://github.com/user-attachments/assets/8c61fc62-3198-48ea-8a4a-d14b8e8cd6e8)
[logs_alde_logs.txt](https://github.com/user-attachments/files/17394108/logs_alde_logs.txt)

**Comment by Fabian-Schmidt** [comment]
The log provided by https://github.com/keshavdv/victron-ble/issues/60 is not usable as it is the Crypted message.

**Comment by HBK1** [comment]
Here is the 1:st values and log, they are from VRM as I do not have access to the RV with bluetooth right now but I can change the ESP remotely. Value change between 13.11 and 13.13 and that is the Output V of the charger and not the battery V as it is 13.10V

![IMG_2210](https://github.com/user-attachments/assets/7eef3a89-a0cc-480e-b04c-43db240e6fb8)
[logs_alde_logs (2).txt](https://github.com/user-attachments/files/17450493/logs_alde_logs.2.txt)

Will try to change to Charging instead of PS remotely and will upload this later.

**Comment by HBK1** [comment]
Here is charging in Bulk.
![IMG_2211](https://github.com/user-attachments/assets/36a220c8-7e29-458a-96af-0d30a2ba9fe2)

[logs_alde_logs (1).txt](https://github.com/user-attachments/files/17450582/logs_alde_logs.1.txt)

**Comment by HBK1** [comment]
Missed Float but here is Storage:

![IMG_2212](https://github.com/user-attachments/assets/3ed8cd8c-a4a1-4505-8168-443473e4ce31)

[logs_alde_logs (5).txt](https://github.com/user-attachments/files/17459286/logs_alde_logs.5.txt)

**Comment by Fabian-Schmidt** [comment]
Hi,
I updated the branch and implemented the main aspects.
Please test it and let me know if it is working.

Supported should be the following sensors:

- sensor
  - `BATTERY_CURRENT`
  - `BATTERY_VOLTAGE`
  - `BATTERY_POWER`
  - `TEMPERATURE`
- text_sensor
  - `DEVICE_STATE`
  - `CHARGER_ERROR`

You might need to set `refresh` on the component to force a reload.

```yaml
external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble@PheonixSmartCharger
    refresh: 0s
```

It will take a while until I can finalize the PR and this issue as I am currently traveling and I don't have access to my normal dev machine.

**Comment by HBK1** [comment]
Result from this config:
sensor:
```
  # MySmart230
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Power"
    type: BATTERY_POWER
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 Battery Temp"
    type: TEMPERATURE

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: MySmart230
    name: "230 has Error"
    type: CHARGER_ERROR


```
![IMG_2214](https://github.com/user-attachments/assets/a0d78287-7d0d-40c1-bcf0-bfd203980667)
![IMG_2213](https://github.com/user-attachments/assets/ca8477fd-6eed-45aa-a7e6-1e6302bdbaea)
[logs_alde_logs (6).txt](https://github.com/user-attachments/files/17460673/logs_alde_logs.6.txt)
