### ISSUE TITLE
Documentation for Blue Smart (Device state eg.)

### ISSUE THREAD

**Issue by Donixon** [Fabian-Schmidt/esphome-victron_ble#74]
With some great luck I managed to make this repo work with our Blue Smart victron device. I'm now looking for documentation for example 'DEVICE_STATE'. It gives back '6', but what does this state mean for this device? I can't it anywhere in the docs. Hopefully someone can direct me somewhere! 

```
sensor:
  # BlueSmart001
  - platform: victron_ble
    victron_ble_id: bluesmart001
    name: "BS001 - Battery voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: bluesmart001
    name: "BS001 - Current" 
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: bluesmart001
    name: "BS001 - Battery power"
    type: BATTERY_POWER
  - platform: victron_ble
    victron_ble_id: bluesmart001
    name: "BS001 - State"
    type: DEVICE_STATE
```

![image](https://github.com/user-attachments/assets/a009a315-2ab2-4e32-ad50-aed744c3b18a)

**Comment by HBK1** [comment]
DEVICE_STATE is a text_sensor:

**Comment by Fabian-Schmidt** [comment]
Hi @Donixon ,
As HBK1 said the device state can either be used a sensor (what you used) or as a text sensor.
Just update your yaml file:

```yaml
text_sensor:
  - platform: victron_ble
    victron_ble_id: bluesmart001
    name: "BS001 - State"
    type: DEVICE_STATE
```

**Comment by xbmcnut** [comment]
@Donixon 

Here's my full working config.

```
sensor:
  # BlueSmartCharger
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Battery Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Charge Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Battery Power"
    type: BATTERY_POWER    
  # - platform: victron_ble
  #   victron_ble_id: BlueSmartCharger
  #   name: "Temperature"
  #   type: TEMPERATURE

binary_sensor:
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Bulk"
    type: DEVICE_STATE_BULK
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Absorption"
    type: DEVICE_STATE_ABSORPTION
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Float"
    type: DEVICE_STATE_FLOAT
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Storage"
    type: DEVICE_STATE_STORAGE
text_sensor:
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "Error"
    type: CHARGER_ERROR
  - platform: victron_ble
    victron_ble_id: BlueSmartCharger
    name: "State"
    type: DEVICE_STATE
```
