### ISSUE TITLE
Clear display values if nothing recieved

### ISSUE THREAD

**Issue by BurlyOaf** [Fabian-Schmidt/esphome-victron_ble#88]
This is awesome, love your work!
I was wondering though, it may be simple and something I just haven't discovered / learnt.

If say we went out of bluetooth range, could the values displayed go blank until  new values are received?

**Comment by Fabian-Schmidt** [comment]
There is no out of the box way in ESPHome. But it could be added either via a script or into this component.

The idea is you have a script which sets a flag:

```yaml
script:
  - id: victron_present_reset
    then:
      - delay: 60s
      - globals.set:
          id: victron_present
          value: 'false'

globals:
  - id: victron_present
    type: bool
    restore_value: false
    initial_value: 'false'
```

And in the on_message event you reset it.

```yaml
victron_ble:
  - id: MySmartShunt
    mac_address: ${smart_shunt_mac_address}
    bindkey: ${smart_shunt_encryption_key}
    on_message:
      then:
        - lambda: |-
            id(victron_present_reset).stop();
            id(victron_present_reset).execute();
```

And in the display you check the global variable:

```yaml
if (!id(victron_present)) {
  // Victron device stale
} else {
  // Victron device fresh
}
```
